# Reference: https://build-cpp.github.io/cmkr/cmake-toml
# to build:
# > cmake -B build
# > cmake --build build --config Release
[project]
name = "uevr-proj"
cmake-before=""" 
add_compile_options($<$<CXX_COMPILER_ID:MSVC>:/MP>)
"""
cmake-after = """
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /MP")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /MP")

set(ASMJIT_STATIC ON CACHE BOOL "" FORCE)

if ("${CMAKE_BUILD_TYPE}" MATCHES "Release")
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /MT")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /MT")

    # Statically compile runtime
    string(REGEX REPLACE "/MD" "/MT" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
    string(REGEX REPLACE "/MD" "/MT" CMAKE_C_FLAGS "${CMAKE_C_FLAGS}")
    string(REGEX REPLACE "/MD" "/MT" CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE}")
    string(REGEX REPLACE "/MD" "/MT" CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE}")

    message(NOTICE "Building in Release mode")
endif()

set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")

add_subdirectory(dependencies/submodules/UESDK)
"""

[target.spdlog]
type = "static"
sources = ["dependencies/submodules/spdlog/src/*.cpp"]
include-directories = ["dependencies/submodules/spdlog/include"]
compile-definitions = ["SPDLOG_COMPILED_LIB"]
alias="spdlog::spdlog"

[target.glm]
type = "static"
sources = ["dependencies/submodules/glm/glm/**.cpp"]
include-directories = ["dependencies/submodules/glm"]

[fetch-content.bddisasm]
git = "https://github.com/bitdefender/bddisasm"
tag = "v1.34.10"

[fetch-content.kananlib]
git = "https://github.com/cursey/kananlib"
tag = "ba66ffaeecfd201ac66310ddf0a4a98140f1441f"

[fetch-content.safetyhook]
git = "https://github.com/praydog/safetyhook"
tag = "4dce6a63268fc0a563f09a4e195b27ad847f9714"
cmake-before="""
set(SAFETYHOOK_FETCH_ZYDIS ON)
"""

[fetch-content.sdkgenny]
git = "https://github.com/cursey/sdkgenny"
tag = "f58077f8da8a271490c17558e93b75843b3afd19"

[fetch-content.openxr]
git = "https://github.com/KhronosGroup/OpenXR-SDK"
tag = "458984d7f59d1ae6dc1b597d94b02e4f7132eaba"

[fetch-content.json]
git = "https://github.com/nlohmann/json"
tag = "bc889afb4c5bf1c0d8ee29ef35eaaf4c8bef8a5d"

[fetch-content.asmjit]
git = "https://github.com/asmjit/asmjit.git"
tag = "2a706fd2ba355808cada31ac1eed8ce28caa6b37"

[fetch-content.tracy]
git = "https://github.com/wolfpld/tracy"
tag = "897aec5b062664d2485f4f9a213715d2e527e0ca"
cmake-before="""
set(TRACY_STATIC ON CACHE BOOL "" FORCE)
set(TRACY_ENABLE OFF CACHE BOOL "" FORCE)
"""

[fetch-content.directxtk]
git = "https://github.com/microsoft/DirectXTK"
tag = "f5026eb34e7053b1aff325d38db107703f394974"
cmake-before="""
set(BUILD_TOOLS OFF CACHE BOOL "" FORCE)
"""
cmake-after="""
if(CMAKE_CXX_COMPILER_VERSION VERSION_GREATER_EQUAL 19.35)
    target_compile_options(DirectXTK PRIVATE /Zc:templateScope-)
endif()
"""

[fetch-content.directxtk12]
git = "https://github.com/microsoft/DirectXTK12"
tag = "528801aa6dd8d628c2f756c41a76d300f47de478"
cmake-before="""
set(BUILD_TOOLS OFF CACHE BOOL "" FORCE)
"""
cmake-after="""
if(CMAKE_CXX_COMPILER_VERSION VERSION_GREATER_EQUAL 19.35)
    target_compile_options(DirectXTK12 PRIVATE /Zc:templateScope-)
endif()
"""

[target.openvr]
type = "shared"
sources = ["dependencies/openvr/src/**.cpp", "dependencies/openvr/src/vrcommon/**.cpp"]
include-directories = ["dependencies/openvr/headers"]
compile-definitions = ["VR_API_PUBLIC", "WIN64"]
alias = "openvr_api"

[target.openvr.properties]
OUTPUT_NAME = "openvr_api"

[target.imgui]
type = "static"
sources = ["dependencies/submodules/imgui/*.cpp"]
include-directories = ["dependencies/submodules/imgui", "src/uevr-imgui"]
compile-definitions = [
    "IMGUI_USER_CONFIG=\"${CMAKE_CURRENT_SOURCE_DIR}/src/uevr-imgui/uevr_imconfig.hpp\"",
]

[target.plugin_renderlib]
type = "static"
sources = ["examples/renderlib/**.cpp", "examples/renderlib/**.c"]
headers = ["examples/renderlib/**.hpp", "examples/renderlib/**.h"]
include-directories = ["examples/renderlib", "include/"]
compile-options = ["/EHa", "/MP"]
compile-features = ["cxx_std_23"]
link-libraries = [
    "imgui"
]

[template.plugin]
type = "shared"
include-directories = ["include/", "examples/renderlib"]
compile-features = ["cxx_std_23"]
link-libraries = [
    "plugin_renderlib",
]

[target.example_plugin]
type = "plugin"
sources = ["examples/example_plugin/**.cpp", "examples/example_plugin/**.c"]
headers = ["examples/example_plugin/**.hpp", "examples/example_plugin/**.h"]

[target.sdk-test]
type = "shared"
sources = ["side-projects/sdk-test/**.cpp", "side-projects/sdk-test/**.c"]
headers = ["side-projects/sdk-test/**.hpp", "side-projects/sdk-test/**.h"]
include-directories = ["shared/", "include/"]
compile-features = ["cxx_std_23"]
link-libraries = [
    "kananlib",
    "uesdk"
]

[target.vr-plugin-nullifier]
type = "shared"
sources = ["vr-plugin-nullifier/**.cpp", "vr-plugin-nullifier/**.c"]
compile-options = ["/GS-", "/EHa", "/MP"]
compile-features = ["cxx_std_23"]
link-libraries = [
    "kananlib"
]

[target.vr-plugin-nullifier.properties]
OUTPUT_NAME = "UEVRPluginNullifier"
RUNTIME_OUTPUT_DIRECTORY_RELEASE = "${CMAKE_BINARY_DIR}/bin/${CMKR_TARGET}"
RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO = "${CMAKE_BINARY_DIR}/bin/${CMKR_TARGET}"
LIBRARY_OUTPUT_DIRECTORY_RELEASE = "${CMAKE_BINARY_DIR}/lib/${CMKR_TARGET}"
LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO = "${CMAKE_BINARY_DIR}/lib/${CMKR_TARGET}"
ARCHIVE_OUTPUT_DIRECTORY_RELEASE = "${CMAKE_BINARY_DIR}/lib/${CMKR_TARGET}"
ARCHIVE_OUTPUT_DIRECTORY_RELWITHDEBINFO = "${CMAKE_BINARY_DIR}/lib/${CMKR_TARGET}"

[target.lua]
type = "static"
sources = ["dependencies/lua/src/*.c"]
include-directories = ["dependencies/lua/src"]

[target.sol2]
type = "interface"
include-directories = ["dependencies/sol2/single/single/include"]

[target.LuaVR]
type = "shared"
compile-features = ["cxx_std_23"]
include-directories = ["include/"]
sources = ["lua-api/**.cpp", "lua-api/**.c"]
headers = ["lua-api/**.hpp", "lua-api/**.h"]
link-libraries = [
    "lua",
    "sol2",
]

[target.LuaVR.properties]
RUNTIME_OUTPUT_DIRECTORY_RELEASE = "${CMAKE_BINARY_DIR}/bin/${CMKR_TARGET}"
RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO = "${CMAKE_BINARY_DIR}/bin/${CMKR_TARGET}"
LIBRARY_OUTPUT_DIRECTORY_RELEASE = "${CMAKE_BINARY_DIR}/lib/${CMKR_TARGET}"
LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO = "${CMAKE_BINARY_DIR}/lib/${CMKR_TARGET}"
ARCHIVE_OUTPUT_DIRECTORY_RELEASE = "${CMAKE_BINARY_DIR}/lib/${CMKR_TARGET}"
ARCHIVE_OUTPUT_DIRECTORY_RELWITHDEBINFO = "${CMAKE_BINARY_DIR}/lib/${CMKR_TARGET}"

[template.ue4template]
type = "shared"
sources = ["src/**.cpp", "src/**.c"]
headers = ["src/**.hpp", "src/**.h"]
include-directories = [
    "shared/", 
    "src/", 
    "include/", 
    "${OPENXR_SOURCE_DIR}/src"
]
compile-options = ["/GS-", "/bigobj", "/EHa", "/MP"]
compile-features = ["cxx_std_23"]
compile-definitions = []
link-libraries = [
    "shlwapi",
    "d3d11",
    "d3d12",
    "safetyhook",
    "glm",
    "imgui",
    "openvr_api",
    "openxr_loader",
    "nlohmann_json",
    "Version",
    "TracyClient",
    "DirectXTK",
    "DirectXTK12",
    "sdkgenny",
    "asmjit"
]

[template.ue4template.properties]
OUTPUT_NAME = "UEVRBackend"
LINK_FLAGS = "/DELAYLOAD:openvr_api.dll"
RUNTIME_OUTPUT_DIRECTORY_RELEASE = "${CMAKE_BINARY_DIR}/bin/${CMKR_TARGET}"
RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO = "${CMAKE_BINARY_DIR}/bin/${CMKR_TARGET}"
LIBRARY_OUTPUT_DIRECTORY_RELEASE = "${CMAKE_BINARY_DIR}/lib/${CMKR_TARGET}"
LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO = "${CMAKE_BINARY_DIR}/lib/${CMKR_TARGET}"
ARCHIVE_OUTPUT_DIRECTORY_RELEASE = "${CMAKE_BINARY_DIR}/lib/${CMKR_TARGET}"
ARCHIVE_OUTPUT_DIRECTORY_RELWITHDEBINFO = "${CMAKE_BINARY_DIR}/lib/${CMKR_TARGET}"

[target.uevr]
type="ue4template"
link-libraries = [
    "kananlib",
    "uesdk"
]
cmake-after="""
add_custom_command(
    TARGET uevr POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy_if_different $<TARGET_FILE:openvr> $<TARGET_FILE_DIR:uevr>)
"""
